proyecto/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme', views.aboutme, name='aboutme'),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

proyecto/proyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/core/models.py
from django.db import models

# Create your models here.

proyecto/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

proyecto/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import CustomUserCreationForm, UserProfileForm


def index(request):
    return render(request, 'core/index.html')

def aboutme(request):
    return render(request, 'core/aboutme.html')


class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')


class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')

    def get_object(self):
        # Devuelve el usuario actual, si no, Django va a esperar un pk en la URL
        return self.request.user

proyecto/core/templates/core/aboutme.html
{% extends 'core/base.html' %}

{% block header %}

{% endblock header %}

{% block main %}
        <!-- Header-->
        <header id="aboutme" class="py-5">
            <div class="container px-5">
                <div class="row justify-content-center">
                    <div class="col-lg-6 d-flex align-items-center justify-content-center">
                        <!-- Imagen en el lado izquierdo -->
                        <img src="media/fotocarnet.jpg" alt="Descripción de la imagen" class="img-fluid w-50">
                    </div>
                    <div class="col-lg-6 col-xxl-6">
                        <div class="text-center my-5">
                            <h1 class="fw-bolder mb-3">¡Hola! Mi nombre es Fabrizio y soy el creador de Pádel Shop.</h1>
                            <p class="lead fw-normal text-muted mb-4">Tengo 25 años y desde que tengo uso de razón, las computadoras son parte de mi vida. Como te imaginarás... también el pádel, mi principal hobbie desde que era niño. </p>
                            <p class="lead fw-normal text-muted mb-4">Te invito a que conozcas en detalle una de mis primeras páginas web programadas con Python. </p>
                            
                        </div>
                    </div>
                </div>
            </div>
        </header>
    
    <!-- About Me section end -->
{% endblock main %}

proyecto/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pádel Shop</title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'core/assets/favicon.ico' %}  " />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
              rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
        <!-- links para trabajar sin el tema -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
       rel="stylesheet"
       integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
       crossorigin="anonymous" /> -->
        <!-- <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            {% include 'core/componentes/navbar.html' %}
            <!-- Blog preview section-->
            <section class="py-3">
                <div class="container px-5 my-1">
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-8 col-xl-6">
                            <div class="text-center">
                                <h2 class="fw-bolder">

                                    {% block header %}
                                    {% endblock header %}

                                </h2>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="py-3">
                <div class="container px-5 my-1">
                    <div class="row gx-5 justify-content-center">
                        {% block main %}
                        {% endblock main %}
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        {% include 'core/componentes/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %} "></script>
    </body>
</html>

proyecto/core/templates/core/basetmp.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Coderhouse</title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'core/assets/favicon.ico' %}  " />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
              rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
        <!-- links para trabajar sin el tema -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
       rel="stylesheet"
       integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
       crossorigin="anonymous" /> -->
        <!-- <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            {% include 'core/componentes/navbar.html' %}
            <!-- Blog preview section-->
            <section class="py-3">
                <div class="container px-5 my-1">
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-8 col-xl-6">
                            <div class="text-center">
                                <h2 class="fw-bolder">

                                    {% block header %}
                                    {% endblock header %}

                                </h2>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="py-3">
                <div class="container px-5 my-1">
                    <div class="row gx-5 justify-content-center">
                        {% block main %}
                        {% endblock main %}
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        {% include 'core/componentes/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %} "></script>
    </body>
</html>

proyecto/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block main %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container">
            <div class="row gx-5 align-items-center justify-content-center">
                <div class="col-lg-8 col-xl-7 col-xxl-6">
                    <div class="my-5 text-center text-xl-start">
                        
                        <h1 class="display-5 fw-bolder text-white mb-2">Encontra las mejores paletas en Pádel Shop</h1>
                        <h1 class="display-5 fw-bolder text-white mb-2"></h1>
                        <p class="lead fw-normal text-white-50 mb-4">
                            
                        </p>
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#productos">Productos</a>
                            <a class="btn btn-outline-light btn-lg px-4" href="#contacto">Contacto</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                    <img class="img-fluid rounded-3 my-5"
                         src="media/padel1.jpg"
                         alt="..." />
                </div>
            </div>
        </div>
    </header>
    <!-- Features section-->

    <section id="productos" class="py-5" id="features">
        <div class="container px-5 my-3">
            <div class="row gx-5 row-cols-1 row-cols-md-3">
                {% include 'core/componentes/card.html' with titulo="Bullpadel Vertex 04" texto="Esto sirve para tu negocio" imagen_url="media/vertex04.jpg" url="productos/comprar"%}
                {% include 'core/componentes/card.html' with titulo="Varlion Summum Prisma" texto="Esto sirve para tu negocio" imagen_url="media/summumprima.jpg" url="productos/comprar"%}
                {% include 'core/componentes/card.html' with titulo="Bullpadel Neuron 24" texto="Esto sirve para tu negocio" imagen_url="media/neuron24.jpg" url="productos/comprar"%}
                {% include 'core/componentes/card.html' with titulo="Bullpadel BP10" texto="Esto sirve para tu negocio" imagen_url="media/bp10.jpg" url="productos/comprar"%}
                {% include 'core/componentes/card.html' with titulo="Adidas Zukur CTRL" texto="Esto sirve para tu negocio" imagen_url="media/adidaszukur.jpg" url="productos/comprar"%}
                {% include 'core/componentes/card.html' with titulo="Bullpadel Hack 04" texto="Esto sirve para tu negocio" imagen_url="media/hack04.jpg" url="productos/comprar"%}
            </div>
        </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8">
                    
                </div>
            </div>
        </div>
    </section>
    <!-- Testimonial section-->
    <!-- Call to action-->
    <aside id="contacto" class="bg-primary bg-gradient rounded-3 p-4 p-sm-5 mt-5">
        <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
            <div class="mb-4 mb-xl-0">
                <div class="fs-3 fw-bold text-white">¿No encontras lo que estás buscando?</div>
                <div class="text-white-50">Suscribite a nuestro newsletter para enterarte de los nuevos ingresos antes que nadie.</div>
            </div>
            <div class="ms-xl-4">
                <div class="input-group mb-2">
                    <input class="form-control"
                           type="text"
                           placeholder="Escribe tu email..."
                           aria-label="Email address..."
                           aria-describedby="button-newsletter" />
                    
                    <a href="#" class="btn btn-outline-light" id="subscribe-button">Enviar</a>

                    <script>
                        document.getElementById("subscribe-button").onclick = function (event) {
                            event.preventDefault();  
                            alert("Gracias por suscribirte al newsletter de Pádel Shop");
                            window.location.href = "{% url 'core:index' %}"; 
                        };
                    </script>
                    
                </div>
            </div>
        </aside>
{% endblock main %}

proyecto/core/templates/core/indexmp.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block main %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container">
            <div class="row gx-5 align-items-center justify-content-center">
                <div class="col-lg-8 col-xl-7 col-xxl-6">
                    <div class="my-5 text-center text-xl-start">
                        <h1 class="display-5 fw-bolder text-white mb-2">La Caja de Pandora</h1>
                        <p class="lead fw-normal text-white-50 mb-4">
                            Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit!
                        </p>
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#features">Get Started</a>
                            <a class="btn btn-outline-light btn-lg px-4" href="#!">Learn More</a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                    <img class="img-fluid rounded-3 my-5"
                         src="{% static 'core/img/caja-pandora.webp' %}"
                         alt="..." />
                </div>
            </div>
        </div>
    </header>
    <!-- Features section-->
    <section class="py-5" id="features">
        <div class="container px-5 my-5">
            <div class="row gx-5">
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h2 class="fw-bolder mb-0">A better way to start building.</h2>
                </div>
                <div class="col-lg-8">
                    <div class="row gx-5 row-cols-1 row-cols-md-2">
                        {% include 'core/componentes/card.html' with titulo="Mi producto 1" texto="Esto sirve para tu negocio" %}
                        {% include 'core/componentes/card.html' with titulo="Mi producto 2" texto="Esto sirve para tu negocio" %}
                        {% include 'core/componentes/card.html' with titulo="Mi producto 3" texto="Esto sirve para tu negocio" %}
                        {% include 'core/componentes/card.html' with titulo="Mi producto 4" texto="Esto sirve para tu negocio" %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Testimonial section-->
    <div class="py-5 bg-light">
        <div class="container px-5 my-5">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-10 col-xl-7">
                    <div class="text-center">
                        <div class="fs-4 mb-4 fst-italic">
                            "Working with Start Bootstrap templates has saved me tons of development time when building new projects! Starting with a Bootstrap template just makes things easier!"
                        </div>
                        <div class="d-flex align-items-center justify-content-center">
                            <img class="rounded-circle me-3"
                                 src="https://dummyimage.com/40x40/ced4da/6c757d"
                                 alt="..." />
                            <div class="fw-bold">
                                Tom Ato
                                <span class="fw-bold text-primary mx-1">/</span>
                                CEO, Pomodoro
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row gx-5">
        <div class="col-lg-4 mb-5">
            <div class="card h-100 shadow border-0">
                <img class="card-img-top"
                     src="https://dummyimage.com/600x350/ced4da/6c757d"
                     alt="..." />
                <div class="card-body p-4">
                    <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                    <a class="text-decoration-none link-dark stretched-link" href="#!">
                        <h5 class="card-title mb-3">Blog post title</h5>
                    </a>
                    <p class="card-text mb-0">
                        Some quick example text to build on the card title and make up the bulk of the card's content.
                    </p>
                </div>
                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                    <div class="d-flex align-items-end justify-content-between">
                        <div class="d-flex align-items-center">
                            <img class="rounded-circle me-3"
                                 src="https://dummyimage.com/40x40/ced4da/6c757d"
                                 alt="..." />
                            <div class="small">
                                <div class="fw-bold">Kelly Rowan</div>
                                <div class="text-muted">March 12, 2023 &middot; 6 min read</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-5">
            <div class="card h-100 shadow border-0">
                <img class="card-img-top"
                     src="https://dummyimage.com/600x350/adb5bd/495057"
                     alt="..." />
                <div class="card-body p-4">
                    <div class="badge bg-primary bg-gradient rounded-pill mb-2">Media</div>
                    <a class="text-decoration-none link-dark stretched-link" href="#!">
                        <h5 class="card-title mb-3">Another blog post title</h5>
                    </a>
                    <p class="card-text mb-0">
                        This text is a bit longer to illustrate the adaptive height of each card. Some quick example text to build on the card title and make up the bulk of the card's content.
                    </p>
                </div>
                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                    <div class="d-flex align-items-end justify-content-between">
                        <div class="d-flex align-items-center">
                            <img class="rounded-circle me-3"
                                 src="https://dummyimage.com/40x40/ced4da/6c757d"
                                 alt="..." />
                            <div class="small">
                                <div class="fw-bold">Josiah Barclay</div>
                                <div class="text-muted">March 23, 2023 &middot; 4 min read</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-5">
            <div class="card h-100 shadow border-0">
                <img class="card-img-top"
                     src="https://dummyimage.com/600x350/6c757d/343a40"
                     alt="..." />
                <div class="card-body p-4">
                    <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                    <a class="text-decoration-none link-dark stretched-link" href="#!">
                        <h5 class="card-title mb-3">The last blog post title is a little bit longer than the others</h5>
                    </a>
                    <p class="card-text mb-0">
                        Some more quick example text to build on the card title and make up the bulk of the card's content.
                    </p>
                </div>
                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                    <div class="d-flex align-items-end justify-content-between">
                        <div class="d-flex align-items-center">
                            <img class="rounded-circle me-3"
                                 src="https://dummyimage.com/40x40/ced4da/6c757d"
                                 alt="..." />
                            <div class="small">
                                <div class="fw-bold">Evelyn Martinez</div>
                                <div class="text-muted">April 2, 2023 &middot; 10 min read</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Call to action-->
    <aside class="bg-primary bg-gradient rounded-3 p-4 p-sm-5 mt-5">
        <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
            <div class="mb-4 mb-xl-0">
                <div class="fs-3 fw-bold text-white">New products, delivered to you.</div>
                <div class="text-white-50">Sign up for our newsletter for the latest updates.</div>
            </div>
            <div class="ms-xl-4">
                <div class="input-group mb-2">
                    <input class="form-control"
                           type="text"
                           placeholder="Email address..."
                           aria-label="Email address..."
                           aria-describedby="button-newsletter" />
                    <button class="btn btn-outline-light" id="button-newsletter" type="button">Sign up</button>
                </div>
                <div class="small text-white-50">We care about privacy, and will never share your data.</div>
            </div>
        </div>
    </aside>
{% endblock main %}

proyecto/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block header %}
    Login
{% endblock header %}

{% block main %}
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            {{ form.username.label_tag }}
            {{ form.username }}
            <div class="invalid-feedback">Por favor, introduce un nombre de usuario válido.</div>
        </div>
        <div class="mb-3">
            {{ form.password.label_tag }}
            {{ form.password }}
            <div class="invalid-feedback">Por favor, introduce una contraseña válida.</div>
        </div>
        <button type="submit" class="btn btn-primary">Iniciar sesión</button>
    </form>
    <p class="mt-3">
        ¿No tienes una cuenta? <a href="{% url 'core:register' %}" class="text-decoration-none">Regístrate aquí</a>
    </p>
{% endblock main %}

proyecto/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block header %}
    Logout
{% endblock header %}

{% block main %}
    <div style="text-align: center;">
        <p>Has cerrado sesión</p>
    </div>
{% endblock main %}

proyecto/core/templates/core/profile.html
{% extends 'core/base.html' %}

{% block header %}
    Actualizar Perfil del Usuario
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock main %}

proyecto/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block header %}
    Registro de Usuario
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrarse</button>
    </form>
{% endblock main %}