proyecto/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme', views.aboutme, name='aboutme'),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

proyecto/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'productos'


urlpatterns = [
    path('', views.index, name='index'),
    # path('productocategoria/list', views.productocategoria_list, name='productocategoria_list'),
    path(
        'productocategoria/list',
        views.ProductoCategoriaList.as_view(),
        name='productocategoria_list',
    ),
    
    path('productos', views.productos , name='productos'),
    #path('pedido/list', views.login_ , name='pedido_list'),
    #path('pedido/create', views.pedido_create , name='pedido_create'),
    path('pedido/list', login_required(views.pedido_list), name='pedido_list'),
    path('pedido/create', login_required(views.pedido_create), name='pedido_create'),
    path('comprar', views.comprar, name='pedido_comprar'),
    path('pedido/detail/<int:pk>', login_required(views.PedidoDetail.as_view()), name='pedido_detail'),
    path('pedido/update/<int:pk>', login_required(views.PedidoUpdate.as_view()), name='pedido_update'),
    path('pedido/delete/<int:pk>', login_required(views.PedidoDelete.as_view()), name='pedido_delete'),
    
    
   
    path(
        'productocategoria/create',
        views.ProductoCategoriaCreate.as_view(),
        name='productocategoria_create',
    ),
    path(
        'productocategoria/detail/<int:pk>',
        views.ProductoCategoriaDetail.as_view(),
        name='productocategoria_detail',
    ),
  
    path(
        'productocategoria/update/<int:pk>',
        views.ProductoCategoriaUpdate.as_view(),
        name='productocategoria_update',
    ),
 
    path(
        'productocategoria/delete/<int:pk>',
        views.ProductoCategoriaDelete.as_view(),
        name='productocategoria_delete',
    ),
]

proyecto/proyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/productos/models.py
from django.db import models
from clientes.models import Cliente


class ProductoCategoria(models.Model):
    """Categorías de productos"""

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    disponible = models.BooleanField(default=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Categoría de Producto'
        verbose_name_plural = 'Categorías de Productos'


class Producto(models.Model):
    
    producto = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    disponible = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f'{self.producto} ${self.precio:.2f}'

        
#Agregados para Pedidos

class Pedido(models.Model):
    class Estado(models.TextChoices):
        PENDIENTE = 'Pendiente', 'Pendiente'
        ENTREGADO = 'Entregado', 'Entregado'
        CANCELADO = 'Cancelado', 'Cancelado'
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    producto = models.ForeignKey(ProductoCategoria, on_delete=models.CASCADE)
    descripcion = models.TextField(blank=True, null=True)
    fecha_solicitud = models.DateTimeField(auto_now_add=True)
    fecha_entrega = models.DateTimeField(blank=True, null=True)
    estado = models.CharField(max_length=20, choices=Estado.choices, default=Estado.PENDIENTE)
    
    def __str__(self) -> str:
        return f"Pedido de {self.producto} para {self.cliente.apellido}, {self.cliente.nombre}"

proyecto/productos/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db import  models
from django.core.validators import RegexValidator
from .models import ProductoCategoria, Pedido, Cliente, Producto


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = ProductoCategoria #ProductoCategoria
        # fields = ['nombre', 'descripcion']
        fields = '__all__'

    def clean_nombre(self):
        nombre: str = self.cleaned_data.get('nombre', '')


        if len(nombre) < 3 or len(nombre) > 50:
            raise ValidationError(
                'El nombre debe tener una longitud mínima de 3 letras o máxima de 50'
            )
        return nombre

#Agregado para Pedidos
   
class PedidoForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(
        queryset=Cliente.objects.all(), empty_label="Seleccione un cliente",
    )
    producto = forms.ModelChoiceField(
        queryset=ProductoCategoria.objects.filter(disponible=True),
        empty_label="Seleccione un producto",
        )
    
    class Meta:
        model = Pedido
        fields = '__all__'
        widgets = {"fecha_entrega": forms.DateTimeInput(attrs={"type": "datetime-local"})}

class CompraForm(forms.ModelForm):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.CharField(
        max_length=15,
        null = True,
        blank = False,
        validators=[
            RegexValidator(r'^\d{10,15}$', 'El número de teléfono debe contener solo números (entre 10 y 15 dígitos).')
        ]
       )
    
    class Meta:
        model = Cliente
        fields = '__all__'
    
    producto = forms.ModelChoiceField(
        queryset=ProductoCategoria.objects.filter(disponible=True),
        empty_label="Seleccione un producto",
        )

proyecto/productos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import ProductoCategoriaForm, PedidoForm, CompraForm
from .models import ProductoCategoria, Pedido
from clientes.models import Cliente
from clientes.forms import ClienteForm


#def index(request):
#    return render(request, 'productos/index.html')

def productos(request):
    return render(request, 'productos/vista_productos.html')


@login_required
def index(request):
    return render(request, 'clientes/index.html')


#CRUDE de Productos

def productocategoria_list(request):
    q = request.GET.get('q')
    if q:
        query = ProductoCategoria.objects.filter(nombre__icontains=q)
    else:
        query = ProductoCategoria.objects.all()
    context = {'object_list': query}
    return render(request, 'productos/productocategoria_list.html', context)


class ProductoCategoriaList(LoginRequiredMixin, ListView):
    model = ProductoCategoria

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = ProductoCategoria.objects.filter(nombre__icontains=q)
        return queryset


def productocategoria_create(request):
    if request.method == 'GET':
        form = ProductoCategoriaForm()

    if request.method == 'POST':
        form = ProductoCategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('productos:productocategoria_list')

    return render(request, 'productos/productocategoria_form.html', {'form': form})


class ProductoCategoriaCreate(LoginRequiredMixin, CreateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy('productos:productocategoria_list')


def productocategoria_detail(request, pk: int):
    query = ProductoCategoria.objects.get(id=pk)
    context = {'object': query}
    return render(request, 'productos/productocategoria_detail.html', context)


class ProductoCategoriaDetail(DetailView):
    model = ProductoCategoria


def productocategoria_update(request, pk: int):
    query = ProductoCategoria.objects.get(id=pk)
    if request.method == 'GET':
        form = ProductoCategoriaForm(instance=query)

    if request.method == 'POST':
        form = ProductoCategoriaForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect('productos:productocategoria_list')

    return render(request, 'productos/productocategoria_form.html', {'form': form})


class ProductoCategoriaUpdate(UpdateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy('productos:productocategoria_list')


def productocategoria_delete(request, pk: int):
    query = ProductoCategoria.objects.get(id=pk)
    if request.method == 'POST':
        query.delete()
        return redirect('productos:productocategoria_list')
    return render(request, 'productos/productocategoria_confirm_delete.html', {'object': query})


class ProductoCategoriaDelete(DeleteView):
    model = ProductoCategoria
    success_url = reverse_lazy('productos:productocategoria_list')


#CRUDE de Pedidos

def pedido_list(request):
    q = request.GET.get('q')
    if q:
        query = Pedido.objects.filter(nombre__icontains=q)
    else:
        query = Pedido.objects.all()
    context = {'object_list': query}
    return render(request, 'productos/pedido_list.html', context)

class PedidoList(LoginRequiredMixin, ListView):
    model = Pedido
    
    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = Pedido.objects.filter(nombre__icontains=q)
        return queryset
    
    # query = Pedido.objects.all()
    # context = {"object_list": query}
    # return render(request, 'productos/pedido_list.html', context)


def pedido_create(request):
    if request.method == "GET":
        form = PedidoForm()
        
    if request.method == "POST":
        form = PedidoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('productos:pedido_list')
        
    return render(request, 'productos/pedido_create.html', {"form":form})

class PedidoCreate(LoginRequiredMixin, CreateView):
    model = Pedido
    form_class = PedidoForm
    success_url = reverse_lazy('productos:pedido_list')

#Pedido detail

def pedido_detail(request, pk: int):
    query = Pedido.objects.get(id=pk)
    context = {'object': query}
    return render(request, 'productos/pedido_detail.html', context)

class PedidoDetail(DetailView):
    model = Pedido
    
#Pedido update

def pedido_update(request, pk: int):
    query = Pedido.objects.get(id=pk)
    if request.method == 'GET':
        form = PedidoForm(instance=query)

    if request.method == 'POST':
        form = PedidoForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect('productos:pedido_list')

    return render(request, 'productos/pedido_create.html', {'form': form})


class PedidoUpdate(UpdateView):
    model = Pedido
    form_class = PedidoForm
    template_name = 'productos/pedido_create.html'
    success_url = reverse_lazy('productos:pedido_list')

#Pedido delete

def pedido_delete(request, pk: int):
    query = Pedido.objects.get(id=pk)
    if request.method == 'POST':
        query.delete()
        return redirect('productos:pedido_list')
    return render(request, 'productos/pedido_confirm_delete.html', {'object': query})


class PedidoDelete(DeleteView):
    model = Pedido
    success_url = reverse_lazy('productos:pedido_list')


#Agregado para Compras

def comprar(request):
    if request.method == "GET":
        form = CompraForm()
        
    if request.method == "POST":
        form = CompraForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            apellido = form.cleaned_data["apellido"]
            telefono = form.cleaned_data["telefono"]
            cliente = Cliente.objects.create(
                nombre=nombre,
                apellido=apellido,
                telefono=telefono
                )
            
            
            producto = form.cleaned_data['producto']
            pedido = Pedido.objects.create(
                 cliente=cliente,
                 producto=producto
            )
            
            
            return redirect('core:index')
        
        
    return render(request, 'productos/comprar.html', {"form":form})

proyecto/productos/templates/productos/comprar.html
{% extends 'core/base.html' %}

{% block header %}
Generar solicitud de pedido
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
{% endblock main %}

proyecto/productos/templates/productos/index.html
{% extends 'core/base.html' %}

{% block header %}
    Productos
{% endblock header %}

{% block main %}
    <div style="display: flex; flex-direction: column; align-items: center">
        <a href="{% url 'productos:productocategoria_list' %}">
            <button>Categorías de Productos</button>
        </a>
    </div>
{% endblock main %}

proyecto/productos/templates/productos/pedido_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
    Borrar producto
{% endblock header %}

{% block main %}
    <p>¿Está seguro que desea borrar el producto "{{ object.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
    </form>
    {% include 'productos/partials/volver_productocategoria.html' %}
{% endblock main %}

proyecto/productos/templates/productos/pedido_create.html
{% extends 'core/base.html' %}

{% block header %}
Generar pedido
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
{% endblock main %}

proyecto/productos/templates/productos/pedido_detail.html
{% extends 'core/base.html' %}

{% block header %}
    Vista en detalle de Pedidos
{% endblock header %}

{% block main %}
    <ul>
        <li>
            <strong>Nombre:</strong> {{ object.producto }}
        </li>
        <li>
            <strong>Descripción:</strong> {{ object.descripcion }}
        </li>
        <li>
            <strong>Precio:</strong> {{ object.precio }}
        </li>
    </ul>
    {% include 'productos/partials/volver_pedido.html' %}
{% endblock main %}

proyecto/productos/templates/productos/pedido_list.html
{% extends 'core/base.html' %}

{% block header %}
Pedidos
{% endblock header %}



{% block main %}
<div class="container my-4">
    <div class="d-flex justify-content-center">
        <form method="get" class="d-flex me-3">
            <input type="text" class="form-control me-2" name="q" placeholder="Buscar...">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </form>
        <a href="{% url 'productos:pedido_create' %}">
            <button class="btn btn-success">Crear nuevo pedido</button>
        </a>
    </div>

    <div class="table-responsive mt-4"></div>
        <table class="table table-bordered table-striped">
            <thead class="table-dark text-center">
                <tr>
                    <th style="width: 23%;">Producto</th>
                    <th style="width: 23%;">Cliente</th>
                    <th style="width: 23%;">Estado</th>
                    <th style="width: 10%;"></th>
                    <th style="width: 10%;"></th>
                    <th style="width: 10%;"></th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.producto }}</td>
                        <td>{{ object.cliente }}</td>
                        <td>{{ object.estado }}</td>
                        
                        <td class="text-center">
                            <a href="{% url 'productos:pedido_detail' object.id %}" class="btn btn-info btn-sm">Detalle</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'productos:pedido_update' object.id %}" class="btn btn-warning btn-sm">Modificar</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'productos:pedido_delete' object.id %}" class="btn btn-danger btn-sm">Borrar</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">No hay pedidos registrados.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock main %}

proyecto/productos/templates/productos/productocategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
    Borrar producto
{% endblock header %}

{% block main %}
    <p>¿Está seguro que desea borrar el producto "{{ object.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
    </form>
    {% include 'productos/partials/volver_productocategoria.html' %}
{% endblock main %}

proyecto/productos/templates/productos/productocategoria_detail.html
{% extends 'core/base.html' %}

{% block header %}
    Vista en detalle de productos
{% endblock header %}

{% block main %}
    <ul>
        <li>
            <strong>Nombre:</strong> {{ object.nombre }}
        </li>
        <li>
            <strong>Descripción:</strong> {{ object.descripcion }}
        </li>
        <li>
            <strong>Precio:</strong> {{ object.precio }}
        </li>
    </ul>
    {% include 'productos/partials/volver_productocategoria.html' %}
{% endblock main %}

proyecto/productos/templates/productos/productocategoria_form.html
{% extends 'core/base.html' %}

{% block header %}
    {% if form.instance.pk %}
        Actualizar producto
    {% else %}
        Crear producto
    {% endif %}
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
    {% include 'productos/partials/volver_productocategoria.html' %}
{% endblock main %}

proyecto/productos/templates/productos/productocategoria_list.html
{% extends 'core/base.html' %}

{% block header %}
{% endblock header %}

{% block main %}
<div class="container my-4">
    <div class="d-flex justify-content-center">
        <form method="get" class="d-flex me-3">
            <input type="text" class="form-control me-2" name="q" placeholder="Buscar...">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </form>
        <a href="{% url 'productos:productocategoria_create' %}">
            <button class="btn btn-success">Agregar producto</button>
        </a>
    </div>

    <div class="table-responsive mt-4">
        <table class="table table-bordered table-striped">
            <thead class="table-dark text-center">
                <tr>
                    <th style="width: 23%;">Nombre</th>
                    <th style="width: 23%;">Precio</th>
                    <th style="width: 23%;">Disponible</th>
                    <th style="width: 10%;"></th>
                    <th style="width: 10%;"></th>
                    <th style="width: 10%;"></th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.nombre }}</td>
                        <td>{{ object.precio }}</td>
                        <td  class="text-center">
                            {% if object.disponible %}
                                ✔
                                {% else %}
                                ❌
                            {% endif %}
                        
                        </td>
                        <td class="text-center">
                            <a href="{% url 'productos:productocategoria_detail' object.id %}" class="btn btn-info btn-sm">Detalle</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'productos:productocategoria_update' object.id %}" class="btn btn-warning btn-sm">Actualizar</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'productos:productocategoria_delete' object.id %}" class="btn btn-danger btn-sm">Borrar</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">No hay registros</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock main %}

proyecto/productos/templates/productos/vista_productos.html
{% extends 'core/base.html' %}
{% load static %}


{% block header %}
    Todos los productos
{% endblock header %}

{% block main %}
<section id="productos" class="py-5" id="features">
    <div class="container px-5 my-3">
        <div class="row gx-5 row-cols-1 row-cols-md-3">
            {% include 'core/componentes/card.html' with titulo="Bullpadel Vertex 04" texto="Esto sirve para tu negocio" imagen_url="media/vertex04.jpg" url="productos/comprar"%}
            {% include 'core/componentes/card.html' with titulo="Varlion Summum Prisma" texto="Esto sirve para tu negocio" imagen_url="media/summumprima.jpg" %}
            {% include 'core/componentes/card.html' with titulo="Bullpadel Neuron 24" texto="Esto sirve para tu negocio" imagen_url="media/neuron24.jpg" %}
            {% include 'core/componentes/card.html' with titulo="Bullpadel BP10" texto="Esto sirve para tu negocio" imagen_url="media/bp10.jpg" %}
            {% include 'core/componentes/card.html' with titulo="Adidas Zukur CTRL" texto="Esto sirve para tu negocio" imagen_url="media/adidaszukur.jpg" %}
            {% include 'core/componentes/card.html' with titulo="Bullpadel Hack 04" texto="Esto sirve para tu negocio" imagen_url="media/hack04.jpg" %}
        </div>
    </div>
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8">
                
            </div>
        </div>
    </div>
</section>
{% endblock main %}