proyecto/clientes/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'clientes'


urlpatterns = [
    path('', views.index, name='index'),
    path('pais/list', login_required(views.pais_list), name='pais_list'),
    path('pais/create', login_required(views.pais_create), name='pais_create'),
    path('pais/detail/<int:pk>', login_required(views.pais_detail), name='pais_detail'),
    path('list', login_required(views.cliente_list), name='cliente_list'),
    path('cliente/create', login_required(views.cliente_create), name='cliente_create'),
    path('cliente/detail/<int:pk>', login_required(views.ClienteDetail.as_view()), name='cliente_detail'),
    path('cliente/update/<int:pk>', login_required(views.ClienteUpdate.as_view()), name='cliente_update'),
    path('cliente/delete/<int:pk>', login_required(views.ClienteDelete.as_view()), name='cliente_delete'),

    
    
]

proyecto/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme', views.aboutme, name='aboutme'),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

proyecto/proyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/clientes/models.py
from django.db import models
from django.core.validators import RegexValidator


class Pais(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'País de origen'
        verbose_name_plural = 'Países de origen'


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True, blank=True)
    telefono = models.CharField(
        max_length=15,
        null = True,
        blank = False,
        validators=[
            RegexValidator(r'^\d{10,15}$', 'El número de teléfono debe contener solo números (entre 10 y 15 dígitos).')
        ]
    )
    email = models.CharField(max_length=100, null=True, blank=True,)
    pais_origen_id = models.ForeignKey(
        Pais, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='País'
    )

    def __str__(self):
        return f'{self.apellido}, {self.nombre}'

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

proyecto/clientes/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Cliente, Pais


class PaisForm(forms.ModelForm):
    class Meta:
        model = Pais
        fields = '__all__'

    def clean_nombre(self):
        nombre: str = self.cleaned_data.get('nombre', '')

        # Validar que solo contenga letras
        if not nombre.isalpha():
            raise ValidationError('El nombre sólo puede contener letras')

        # Validar longitud de nombre
        if len(nombre) < 3 or len(nombre) > 50:
            raise ValidationError(
                'El nombre debe tener una longitud mínima de 3 letras o máxima de 50'
            )
        return nombre


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'
        widgets = {'nacimiento': forms.DateInput(attrs={'type': 'date'})}

proyecto/clientes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import ClienteForm, PaisForm
from .models import Cliente, Pais


@login_required
def index(request):
    return render(request, 'clientes/index.html')


def pais_list(request):
    q = request.GET.get('q')
    if q:
        query = Pais.objects.filter(nombre__icontains=q)
    else:
        query = Pais.objects.all()
    context = {'object_list': query}
    return render(request, 'clientes/pais_list.html', context)


def pais_create(request):
    if request.method == 'GET':
        form = PaisForm()

    if request.method == 'POST':
        form = PaisForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            form.save()
            return redirect('clientes:pais_list')

    return render(request, 'clientes/pais_form.html', {'form': form})


def pais_detail(request, pk: int):
    query = Pais.objects.get(id=pk)
    context = {'object': query}
    return render(request, 'clientes/pais_detail.html', context)

#Cliente list

def cliente_list(request):
    q = request.GET.get('q')
    if q:
        query = Cliente.objects.filter(nombre__icontains=q)
    else:
        query = Cliente.objects.all()
    context = {'object_list': query}
    return render(request, 'clientes/cliente_list.html', context)

class ClienteList(LoginRequiredMixin, ListView):
    model = Cliente
    # template_name = 'productos/productocategoria_list.html'
    # context_object_name = 'categorias'
    # queryset = ProductoCategoria.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = Cliente.objects.filter(nombre__icontains=q)
        return queryset


#Cliente create

def cliente_create(request):
    if request.method == 'GET':
        form = ClienteForm()

    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clientes:cliente_list')

    return render(request, 'clientes/cliente_form.html', {'form': form})

class ClienteCreate(LoginRequiredMixin, CreateView):
    model = Cliente
    form_class = ClienteForm
    success_url = reverse_lazy('clientes:cliente_list')

#Cliente detail

def cliente_detail(request, pk: int):
    query = Cliente.objects.get(id=pk)
    context = {'object': query}
    return render(request, 'clientes/cliente_detail.html', context)

class ClienteDetail(DetailView):
    model = Cliente
    
#Cliente update

def cliente_update(request, pk: int):
    query = Cliente.objects.get(id=pk)
    if request.method == 'GET':
        form = ClienteForm(instance=query)

    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect('clientes:cliente_list')

    return render(request, 'clientes/cliente_form.html', {'form': form})


class ClienteUpdate(UpdateView):
    model = Cliente
    form_class = ClienteForm
    success_url = reverse_lazy('clientes:cliente_list')

#Cliente delete

def cliente_delete(request, pk: int):
    query = Cliente.objects.get(id=pk)
    if request.method == 'POST':
        query.delete()
        return redirect('clientes:cliente_list')
    return render(request, 'clientes/cliente_confirm_delete.html', {'object': query})


class ClienteDelete(DeleteView):
    model = Cliente
    success_url = reverse_lazy('clientes:cliente_list')

proyecto/clientes/templates/clientes/cliente_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
    Borrar cliente
{% endblock header %}

{% block main %}
    <p>¿Está seguro que desea borrar el cliente "{{ object.apellido}},{{ object.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
    </form>
    {% include 'clientes/partials/volver_cliente.html' %}
{% endblock main %}

proyecto/clientes/templates/clientes/cliente_detail.html
{% extends 'core/base.html' %}

{% block header %}
    Vista en detalle de Clientes
{% endblock header %}

{% block main %}
    <ul>
        <li>
            <strong>Apellido:</strong> {{ object.apellido }}
        </li>
        <li>
            <strong>Nombre:</strong> {{ object.nombre }}
        </li>
        <li>
            <strong>Fecha de nacimiento:</strong> {{ object.nacimiento }}
        </li>
        <li>
            <strong>País:</strong> {{ object.pais_origen_id }}
        </li>
    </ul>
    {% include 'clientes/partials/volver_cliente.html' %}
{% endblock main %}

proyecto/clientes/templates/clientes/cliente_form.html
{% extends 'core/base.html' %}

{% block header %}
    Clientes: Formulario de Clientes
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
    {% include 'clientes/partials/volver_cliente.html' %}
{% endblock main %}

proyecto/clientes/templates/clientes/cliente_list.html
{% extends 'core/base.html' %}

{% block header %}
{% endblock header %}

{% block main %}
<div class="container my-4">

    <div class="d-flex justify-content-center"></div>
        <form method="get" class="d-flex me-3">
            <input type="text" class="form-control me-2" name="q" placeholder="Buscar...">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </form>
        <a href="{% url 'clientes:cliente_create' %}">
            <button class="btn btn-success">Registrar cliente</button>
        </a>
    </div>
    <div class="table-responsive mt-4">
        <table class="table table-bordered table-striped">
            <thead class="table-dark text-center">
                <tr>
                    <th style="width: 23%;">Apellido</th>
                    <th style="width: 23%;">Nombre</th>
                    <th style="width: 23%;">Contacto</th>
                    <th style="width: 10%;"></th>
                    <th style="width: 10%;"></th>
                    <th style="width: 10%;"></th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.apellido | upper }}</td>
                        <td>{{ object.nombre }}</td>
                        <td>{{ object.telefono}}</td>
                        <td class="text-center">
                            <a href="{% url 'clientes:cliente_detail' object.id %}" class="btn btn-info btn-sm">Detalle</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'clientes:cliente_update' object.id %}" class="btn btn-warning btn-sm">Modificar</a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'clientes:cliente_delete' object.id %}" class="btn btn-danger btn-sm">Borrar</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6">No hay registros</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>

{% endblock main %}

proyecto/clientes/templates/clientes/index.html
{% extends 'core/base.html' %}

{% block header %}
    Clientes
{% endblock header %}

{% block main %}
    <div style="display: flex; flex-direction: column ;align-items: center;">
        <a href="{% url 'clientes:cliente_list' %}">
            <button>Clientes</button>
        </a>
        <a href="{% url 'clientes:pais_list' %}">
            <button>Países de origen</button>
        </a>
    </div>
{% endblock main %}

proyecto/clientes/templates/clientes/pais_detail.html
{% extends 'core/base.html' %}

{% block header %}
    Clientes: Vista en Detalle de Países
{% endblock header %}

{% block main %}
    <ul>
        <li>Nombre: {{ object.nombre }}</li>
    </ul>
    {% include 'clientes/partials/volver_pais.html' %}
{% endblock main %}

proyecto/clientes/templates/clientes/pais_form.html
{% extends 'core/base.html' %}

{% block header %}
    Clientes: Formulario de Países
{% endblock header %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
    {% include 'clientes/partials/volver_pais.html' %}
{% endblock main %}

proyecto/clientes/templates/clientes/pais_list.html
{% extends 'core/base.html' %}

{% block header %}
    Clientes: Listado de Países de Origen
{% endblock header %}

{% block main %}
    <div style="display: flex; justify-content: center;">
        <form method="get" style="display: flex; padding-right: 1%;">
            <input type="text" name="q" placeholder="Buscar..." />
            <button type="submit">Buscar</button>
        </form>
        <a href="{% url 'clientes:pais_create' %}">
            <button>Crear Registro</button>
        </a>
    </div>
    <div style="display: flex; justify-content: center;">
        <table>
            <thead>
                <tr>
                    <th style="width: 85%">Nombre</th>
                    <th style="width: 5%"></th>
                    <th style="width: 5%"></th>
                    <th style="width: 5%"></th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.nombre }}</td>
                        <td>
                            <a href="{% url 'clientes:pais_detail' object.id %}">Detalle</a>
                        </td>
                        <td>
                            <a href="#">Cambiar</a>
                        </td>
                        <td>
                            <a href="#">Borrar</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">No hay registros</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include 'clientes/partials/volver_index.html' %}
{% endblock main %}