proyecto/clientes/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'clientes'


urlpatterns = [
    path('', views.index, name='index'),
    path('pais/list', login_required(views.pais_list), name='pais_list'),
    path('pais/create', login_required(views.pais_create), name='pais_create'),
    path('pais/detail/<int:pk>', login_required(views.pais_detail), name='pais_detail'),
    path('list', login_required(views.cliente_list), name='cliente_list'),
    path('cliente/create', login_required(views.cliente_create), name='cliente_create'),
    path('cliente/detail/<int:pk>', login_required(views.ClienteDetail.as_view()), name='cliente_detail'),
    path('cliente/update/<int:pk>', login_required(views.ClienteUpdate.as_view()), name='cliente_update'),
    path('cliente/delete/<int:pk>', login_required(views.ClienteDelete.as_view()), name='cliente_delete'),

    
    
]

proyecto/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme', views.aboutme, name='aboutme'),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

proyecto/productos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'productos'


urlpatterns = [
    path('', views.index, name='index'),
    # path('productocategoria/list', views.productocategoria_list, name='productocategoria_list'),
    path(
        'productocategoria/list',
        views.ProductoCategoriaList.as_view(),
        name='productocategoria_list',
    ),
    
    path('productos', views.productos , name='productos'),
    #path('pedido/list', views.login_ , name='pedido_list'),
    #path('pedido/create', views.pedido_create , name='pedido_create'),
    path('pedido/list', login_required(views.pedido_list), name='pedido_list'),
    path('pedido/create', login_required(views.pedido_create), name='pedido_create'),
    path('comprar', views.comprar, name='pedido_comprar'),
    path('pedido/detail/<int:pk>', login_required(views.PedidoDetail.as_view()), name='pedido_detail'),
    path('pedido/update/<int:pk>', login_required(views.PedidoUpdate.as_view()), name='pedido_update'),
    path('pedido/delete/<int:pk>', login_required(views.PedidoDelete.as_view()), name='pedido_delete'),
    
    
   
    path(
        'productocategoria/create',
        views.ProductoCategoriaCreate.as_view(),
        name='productocategoria_create',
    ),
    path(
        'productocategoria/detail/<int:pk>',
        views.ProductoCategoriaDetail.as_view(),
        name='productocategoria_detail',
    ),
  
    path(
        'productocategoria/update/<int:pk>',
        views.ProductoCategoriaUpdate.as_view(),
        name='productocategoria_update',
    ),
 
    path(
        'productocategoria/delete/<int:pk>',
        views.ProductoCategoriaDelete.as_view(),
        name='productocategoria_delete',
    ),
]

proyecto/proyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('productos/', include('productos.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/core/models.py
from django.db import models

# Create your models here.

proyecto/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

proyecto/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import CustomUserCreationForm, UserProfileForm


def index(request):
    return render(request, 'core/index.html')

def aboutme(request):
    return render(request, 'core/aboutme.html')


class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')


class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')

    def get_object(self):
        # Devuelve el usuario actual, si no, Django va a esperar un pk en la URL
        return self.request.user

proyecto/core/templates/core/componentes/card.html
<div class="col mb-5 h-100 text-center">
    <!-- Imagen encima del título -->
    <img src="{{ imagen_url }}" class="img-fluid mb-3" style="max-height: 250px;" alt="Imagen del producto">
    
    <h2 class="h5" justify="center">{{ titulo }}</h2>
    <p class="mb-0">
        <a href="{{ url }}" class="btn btn-primary btn-lg">Comprar</a>
    </p>
</div>

proyecto/core/templates/core/componentes/footer.html
<footer class="bg-light py-2">
    <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2024 - Fabrizio Casado</div></div>
</footer>

proyecto/core/templates/core/componentes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'core:index' %}">Pádel Shop: tu tienda de pádel🥎</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'core:index' %}">🏠Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#productos">Productos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:aboutme' %}">Sobre mí</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'clientes:cliente_list' %}">Clientes</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'productos:productocategoria_list' %}">Listado de productos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'productos:pedido_list' %}">Pedidos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:profile' %}">{{ user.username }}</a></li>
                    {% if user.vendedor.avatar %}
                    <img src="{{ user.vendedor.avatar.url }}"
                         alt="avatar"
                         style="height: 30px" />
                    {% else %}
                    <img src="{% static 'core/img/perfil.png' %}"
                         alt="avatar"
                         style="height: 30px" />
                    {% endif %}
                <form action="{% url 'core:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>